# Form implementation generated from reading ui file './src/ui/widgets/camera_feed_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widgetCameraFeed(object):
    def setupUi(self, widgetCameraFeed):
        widgetCameraFeed.setObjectName("widgetCameraFeed")
        widgetCameraFeed.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(widgetCameraFeed)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameCameraFeed = QtWidgets.QFrame(parent=widgetCameraFeed)
        self.frameCameraFeed.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCameraFeed.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCameraFeed.setObjectName("frameCameraFeed")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameCameraFeed)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelCameraFeed = QtWidgets.QLabel(parent=self.frameCameraFeed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCameraFeed.sizePolicy().hasHeightForWidth())
        self.labelCameraFeed.setSizePolicy(sizePolicy)
        self.labelCameraFeed.setObjectName("labelCameraFeed")
        self.verticalLayout_2.addWidget(self.labelCameraFeed, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.frameCameraFeed)

        self.retranslateUi(widgetCameraFeed)
        QtCore.QMetaObject.connectSlotsByName(widgetCameraFeed)

    def retranslateUi(self, widgetCameraFeed):
        _translate = QtCore.QCoreApplication.translate
        widgetCameraFeed.setWindowTitle(_translate("widgetCameraFeed", "Form"))
        self.labelCameraFeed.setText(_translate("widgetCameraFeed", "Camera not active"))
